{{- $licenseKeyAlpha := include "newrelic-logging.licenseKeyAlpha" . -}}
{{- if $licenseKeyAlpha }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic-logging.labels" . | indent 4 }}
  name: {{ template "newrelic-logging.fullname" . }}-config-alpha
type: Opaque
data:
  license-alpha: {{ $licenseKeyAlpha | b64enc }}
{{- end }}
---
{{- $licenseKeyBravo := include "newrelic-logging.licenseKeyBravo" . -}}
{{- if $licenseKeyBravo }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic-logging.labels" . | indent 4 }}
  name: {{ template "newrelic-logging.fullname" . }}-config-bravo
type: Opaque
data:
  license-bravo: {{ $licenseKeyBravo | b64enc }}
{{- end }}
---
{{- $licenseKeyCharlie := include "newrelic-logging.licenseKeyCharlie" . -}}
{{- if $licenseKeyCharlie }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic-logging.labels" . | indent 4 }}
  name: {{ template "newrelic-logging.fullname" . }}-config-charlie
type: Opaque
data:
  license-charlie: {{ $licenseKeyCharlie | b64enc }}
{{- end }}
