apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license-key
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  license: {{ .Values.newRelicLicenseKey | b64enc }}
